/**
 * Traefik Configuration Generator
 * Generates traefik.yml (static config) and dynamic.yml (middlewares)
 */

import { writeFile, mkdir } from "node:fs/promises"
import { existsSync } from "node:fs"
import { join } from "node:path"
import { createHash } from "node:crypto"
import type { EasiarrConfig } from "../config/schema"
import { debugLog } from "../utils/debug"

export interface TraefikStaticConfig {
  entrypoints: {
    web: { address: string }
  }
  api: {
    dashboard: boolean
    insecure: boolean
  }
  providers: {
    docker: {
      endpoint: string
      exposedByDefault: boolean
    }
    file: {
      directory: string
      watch: boolean
    }
  }
}

/**
 * Generate traefik.yml static configuration
 */
export function generateTraefikStaticConfig(): string {
  return `# Traefik Static Configuration
# Generated by easiarr

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: "/etc/traefik"
    watch: true
`
}

/**
 * Generate dynamic.yml with security headers middleware
 */
export function generateTraefikDynamicConfig(
  _middlewares: string[],
  basicAuth?: { username: string; passwordHash: string }
): string {
  let yaml = `# Traefik Dynamic Configuration
# Generated by easiarr

http:
  middlewares:
`

  // Always include security-headers
  yaml += `    security-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
`

  // Add basic-auth middleware if credentials provided
  if (basicAuth?.username && basicAuth?.passwordHash) {
    // Escape $ in password hash for YAML
    const escapedHash = basicAuth.passwordHash.replace(/\$/g, "$$$$")
    yaml += `
    basic-auth:
      basicAuth:
        users:
          - "${basicAuth.username}:${escapedHash}"
`
  }

  return yaml
}

/**
 * Generate htpasswd-compatible hash for basic auth
 * Uses SHA1 hash in htpasswd format: {SHA}base64(sha1(password))
 */
function generateHtpasswdHash(password: string): string {
  const sha1Hash = createHash("sha1").update(password).digest("base64")
  return `{SHA}${sha1Hash}`
}

/**
 * Save Traefik configuration files to the config directory
 */
export async function saveTraefikConfig(config: EasiarrConfig): Promise<void> {
  // Check if traefik is enabled
  const traefikApp = config.apps.find((a) => a.id === "traefik" && a.enabled)
  if (!traefikApp) {
    debugLog("Traefik", "Traefik not enabled, skipping config generation")
    return
  }

  const traefikConfigDir = join(config.rootDir, "config", "traefik")
  const letsencryptDir = join(traefikConfigDir, "letsencrypt")
  debugLog("Traefik", `Generating config in ${traefikConfigDir}`)

  try {
    // Create directories if they don't exist
    if (!existsSync(traefikConfigDir)) {
      await mkdir(traefikConfigDir, { recursive: true })
      debugLog("Traefik", `Created directory: ${traefikConfigDir}`)
    }
    if (!existsSync(letsencryptDir)) {
      await mkdir(letsencryptDir, { recursive: true })
      debugLog("Traefik", `Created directory: ${letsencryptDir}`)
    }

    // Generate and save static config (traefik.yml)
    const staticConfig = generateTraefikStaticConfig()
    const staticPath = join(traefikConfigDir, "traefik.yml")

    // Only write if file doesn't exist (don't overwrite user customizations)
    if (!existsSync(staticPath)) {
      await writeFile(staticPath, staticConfig, "utf-8")
    }

    // Check for basic auth credentials from config
    let basicAuth: { username: string; passwordHash: string } | undefined
    if (config.traefik?.basicAuth?.enabled) {
      const username = config.traefik.basicAuth.username
      const password = config.traefik.basicAuth.password
      if (username && password) {
        basicAuth = {
          username,
          passwordHash: generateHtpasswdHash(password),
        }
      }
    }

    // Generate and save dynamic config (dynamic.yml)
    const dynamicConfig = generateTraefikDynamicConfig(config.traefik?.middlewares ?? [], basicAuth)
    const dynamicPath = join(traefikConfigDir, "dynamic.yml")

    // Always regenerate dynamic.yml as it contains auth settings
    await writeFile(dynamicPath, dynamicConfig, "utf-8")

    // Create acme.json with correct permissions if it doesn't exist
    const acmePath = join(letsencryptDir, "acme.json")
    if (!existsSync(acmePath)) {
      await writeFile(acmePath, "{}", { mode: 0o600 })
    }
  } catch (error) {
    // Permission denied - directory owned by root from Docker
    // User needs to manually create configs or fix permissions
    const err = error as NodeJS.ErrnoException
    if (err.code === "EACCES") {
      console.warn(
        `[WARN] Cannot write Traefik config files (permission denied). ` +
          `Fix with: sudo chown -R $(id -u):$(id -g) ${traefikConfigDir}`
      )
    } else {
      throw error
    }
  }
}
