/**
 * Homepage Configuration Generator
 * Generates services.yaml and other config files for Homepage dashboard
 */

import { writeFile, mkdir } from "node:fs/promises"
import { existsSync } from "node:fs"
import { join } from "node:path"
import type { EasiarrConfig, AppCategory } from "./schema"
import { APP_CATEGORIES } from "./schema"
import { getApp } from "../apps/registry"
import { CATEGORY_ORDER } from "../apps/categories"
import { readEnvSync, getLocalIp, updateEnv } from "../utils/env"
import { PortainerApiClient } from "../api/portainer-api"

/**
 * Get the Homepage config directory path
 */
export function getHomepageConfigPath(config: EasiarrConfig): string {
  return join(config.rootDir, "config", "homepage")
}

/**
 * Homepage service entry
 */
interface HomepageService {
  href: string
  icon?: string
  description?: string
  ping?: string
  widget?: {
    type: string
    url: string
    key?: string
    [key: string]: unknown
  }
}

/**
 * Generate services.yaml content from enabled apps
 */
export async function generateServicesYaml(config: EasiarrConfig): Promise<string> {
  const env = readEnvSync()
  const localIp = getLocalIp()

  // Group apps by category
  const categoryGroups = new Map<AppCategory, Array<{ name: string; service: HomepageService }>>()

  for (const appConfig of config.apps) {
    if (!appConfig.enabled) continue

    const appDef = getApp(appConfig.id)
    if (!appDef) continue

    // Skip homepage itself
    if (appDef.id === "homepage") continue

    const port = appConfig.port ?? appDef.defaultPort
    const baseUrl = `http://${localIp}:${port}`

    const service: HomepageService = {
      href: baseUrl,
      description: appDef.description,
    }

    // Add icon if defined in homepage meta
    if (appDef.homepage?.icon) {
      service.icon = appDef.homepage.icon
    } else {
      // Default to app ID as icon name
      service.icon = `${appDef.id}.png`
    }

    // Add ping for monitoring
    service.ping = baseUrl

    // Add widget if defined and has API key
    if (appDef.homepage?.widget) {
      const apiKey = env[`API_KEY_${appDef.id.toUpperCase()}`]

      service.widget = {
        type: appDef.homepage.widget,
        url: baseUrl,
      }

      if (apiKey) {
        service.widget.key = apiKey
      }

      // Add widget-specific credentials from env
      if (appDef.id === "qbittorrent") {
        const username = env["USERNAME_QBITTORRENT"]
        const password = env["PASSWORD_QBITTORRENT"]
        if (username) service.widget.username = username
        if (password) service.widget.password = password
      }

      if (appDef.id === "portainer") {
        // Try to auto-detect Portainer environment ID
        // User can override with PORTAINER_ENV in .env file
        if (env["PORTAINER_ENV"]) {
          service.widget.env = env["PORTAINER_ENV"]
        } else {
          // Auto-detect from Portainer API
          const portainerPort = appConfig.port ?? appDef.defaultPort
          const portainerClient = new PortainerApiClient(localIp, portainerPort)
          const apiKey = env["API_KEY_PORTAINER"]
          if (apiKey) {
            portainerClient.setApiKey(apiKey)
          }
          const localEnvId = await portainerClient.getLocalEnvironmentId()
          const envIdStr = localEnvId?.toString() ?? "1"
          service.widget.env = envIdStr

          // Persist the detected env ID to .env for future use
          if (localEnvId) {
            await updateEnv({ PORTAINER_ENV: envIdStr })
          }
        }
      }

      // Add any custom widget fields
      if (appDef.homepage.widgetFields) {
        Object.assign(service.widget, appDef.homepage.widgetFields)
      }
    }

    // Add to category group
    const category = appDef.category
    if (!categoryGroups.has(category)) {
      categoryGroups.set(category, [])
    }
    categoryGroups.get(category)!.push({ name: appDef.name, service })
  }

  // Build YAML output
  let yaml = "---\n# Auto-generated by easiarr\n# https://github.com/muhammedaksam/easiarr\n\n"

  // Add easiarr info section with two widgets - one for installed, one for latest
  yaml += `- easiarr:\n`
  // Installed version from local easiarr container
  yaml += `    - Installed:\n`
  yaml += `        href: https://github.com/muhammedaksam/easiarr\n`
  yaml += `        icon: mdi-docker\n`
  yaml += `        description: Your current version\n`
  yaml += `        widget:\n`
  yaml += `          type: customapi\n`
  yaml += `          url: http://easiarr:8080/config.json\n`
  yaml += `          refreshInterval: 3600000\n` // 1 hour
  yaml += `          mappings:\n`
  yaml += `            - field: version\n`
  yaml += `              label: Version\n`
  // Latest version from GitHub API
  yaml += `    - Latest:\n`
  yaml += `        href: https://github.com/muhammedaksam/easiarr/releases\n`
  yaml += `        icon: mdi-github\n`
  yaml += `        description: Check for updates\n`
  yaml += `        widget:\n`
  yaml += `          type: customapi\n`
  yaml += `          url: https://api.github.com/repos/muhammedaksam/easiarr/releases/latest\n`
  yaml += `          headers:\n`
  yaml += `            User-Agent: easiarr-homepage-widget\n`
  yaml += `          refreshInterval: 86400000\n` // 24 hours
  yaml += `          mappings:\n`
  yaml += `            - field: tag_name\n`
  yaml += `              label: Version\n`
  yaml += `            - field: published_at\n`
  yaml += `              label: Released\n`
  yaml += `              format: relativeDate\n`
  yaml += `\n`

  // Use CATEGORY_ORDER for consistent ordering
  for (const { id: category } of CATEGORY_ORDER) {
    const services = categoryGroups.get(category)
    if (!services || services.length === 0) continue

    const categoryName = APP_CATEGORIES[category]
    yaml += `- ${categoryName}:\n`

    for (const { name, service } of services) {
      yaml += `    - ${name}:\n`
      yaml += `        href: ${service.href}\n`

      if (service.icon) {
        yaml += `        icon: ${service.icon}\n`
      }

      if (service.description) {
        yaml += `        description: ${service.description}\n`
      }

      if (service.ping) {
        yaml += `        ping: ${service.ping}\n`
      }

      if (service.widget) {
        yaml += `        widget:\n`
        yaml += `          type: ${service.widget.type}\n`
        yaml += `          url: ${service.widget.url}\n`

        if (service.widget.key) {
          yaml += `          key: ${service.widget.key}\n`
        }

        // Add any other widget fields
        for (const [key, value] of Object.entries(service.widget)) {
          if (key !== "type" && key !== "url" && key !== "key") {
            // Handle mappings array specially
            if (key === "mappings") {
              const mappings = typeof value === "string" ? JSON.parse(value) : value
              if (Array.isArray(mappings)) {
                yaml += `          mappings:\n`
                for (const mapping of mappings) {
                  yaml += `            - field: ${mapping.field}\n`
                  yaml += `              label: ${mapping.label}\n`
                  if (mapping.format) {
                    yaml += `              format: ${mapping.format}\n`
                  }
                }
              }
            } else {
              yaml += `          ${key}: ${value}\n`
            }
          }
        }
      }
    }

    yaml += "\n"
  }

  return yaml
}

/**
 * Generate settings.yaml with sensible defaults
 */
export function generateSettingsYaml(): string {
  return `---
# Auto-generated by easiarr
# For configuration options: https://gethomepage.dev/configs/settings/

title: easiarr Dashboard

# Background: "Close-up Photography of Leaves With Droplets"
# Photo by Sohail Nachiti: https://www.pexels.com/photo/close-up-photography-of-leaves-with-droplets-807598/
background:
  image: https://images.pexels.com/photos/807598/pexels-photo-807598.jpeg?cs=srgb&fm=jpg&w=4128&h=3096
  blur: sm
  saturate: 50
  brightness: 50
  opacity: 50

cardBlur: md
theme: dark
color: slate

layout:
  Media Management:
    style: row
    columns: 4
  Media Servers:
    style: row
    columns: 2
  Download Clients:
    style: row
    columns: 2
`
}

/**
 * Save Homepage configuration files
 */
export async function saveHomepageConfig(config: EasiarrConfig): Promise<{ services: string; settings: string }> {
  const configPath = getHomepageConfigPath(config)

  // Ensure directory exists
  if (!existsSync(configPath)) {
    await mkdir(configPath, { recursive: true })
  }

  const servicesPath = join(configPath, "services.yaml")
  const settingsPath = join(configPath, "settings.yaml")

  // Generate and save services.yaml
  const servicesYaml = await generateServicesYaml(config)
  await writeFile(servicesPath, servicesYaml, "utf-8")

  // Generate and save settings.yaml (only if doesn't exist)
  if (!existsSync(settingsPath)) {
    const settingsYaml = generateSettingsYaml()
    await writeFile(settingsPath, settingsYaml, "utf-8")
  }

  return { services: servicesPath, settings: settingsPath }
}
