/**
 * Recyclarr Configuration Generator
 * Generates recyclarr.yml for automatic TRaSH Guides profile sync
 */

import { mkdir, writeFile } from "node:fs/promises"
import { join } from "node:path"
import YAML from "yaml"
import type { EasiarrConfig, AppId } from "./schema"
import { readEnv } from "../utils/env"
import { debugLog } from "../utils/debug"

/**
 * Get API key for an app from the .env file
 */
async function getAppApiKey(appId: AppId): Promise<string | null> {
  const env = await readEnv()
  const envKey = `API_KEY_${appId.toUpperCase()}`
  return env[envKey] ?? null
}

// TRaSH Guide Custom Format IDs for common unwanted content
const UNWANTED_CFS = {
  radarr: [
    "ed38b889b31be83fda192888e2286d83", // BR-DISK
    "90a6f9a284dff5103f6346090e6280c8", // LQ
    "e204b80c87be9497a8a6eaff48f72905", // LQ (Release Title)
    "dc98083864ea246d05a42df0d05f81cc", // x265 (HD)
    "0a3f082873eb454bde444150b70253cc", // Extras
  ],
  sonarr: [
    "85c61753df5da1fb2aab6f2a47426b09", // BR-DISK
    "9c11cd3f07101cdba90a2d81cf0e56b4", // LQ
    "e2315f990da2e2cbfc9fa5b7a6fcfe48", // LQ (Release Title)
    "47435ece6b99a0b477caf360e79ba0bb", // x265 (HD)
    "fbcb31d8dabd2a319072b84fc0b7249c", // Extras
  ],
}

// TRaSH Guide Quality Definition types
const QUALITY_DEFINITIONS = {
  radarr: "movie",
  sonarr: "series",
}

// Default quality profiles to assign scores to
const DEFAULT_PROFILES = {
  radarr: ["HD", "HD-1080p", "Ultra-HD", "Any"],
  sonarr: ["WEB-1080p", "WEB-DL (1080p)", "HD-1080p", "Any"],
}

interface RecyclarrInstance {
  base_url: string
  api_key: string
  quality_definition?: {
    type: string
    preferred_ratio?: number
  }
  custom_formats?: Array<{
    trash_ids: string[]
    quality_profiles: Array<{
      name: string
    }>
  }>
}

interface RecyclarrConfig {
  radarr?: Record<string, RecyclarrInstance>
  sonarr?: Record<string, RecyclarrInstance>
}

/**
 * Generate recyclarr.yml configuration for enabled *arr apps
 */
export async function generateRecyclarrConfig(config: EasiarrConfig): Promise<string> {
  debugLog("Recyclarr", "Generating recyclarr.yml configuration")

  const recyclarrConfig: RecyclarrConfig = {}

  // Check for enabled Radarr
  const radarrApp = config.apps.find((a) => a.id === "radarr" && a.enabled)
  if (radarrApp) {
    const apiKey = await getAppApiKey("radarr")
    if (apiKey) {
      const port = radarrApp.port ?? 7878
      recyclarrConfig.radarr = {
        radarr_main: {
          base_url: `http://radarr:${port}`,
          api_key: apiKey,
          quality_definition: {
            type: QUALITY_DEFINITIONS.radarr,
            preferred_ratio: 0.5,
          },
          custom_formats: [
            {
              trash_ids: UNWANTED_CFS.radarr,
              quality_profiles: DEFAULT_PROFILES.radarr.map((name) => ({ name })),
            },
          ],
        },
      }
      debugLog("Recyclarr", "Added Radarr configuration")
    } else {
      debugLog("Recyclarr", "Radarr enabled but no API key found - skipping")
    }
  }

  // Check for enabled Sonarr
  const sonarrApp = config.apps.find((a) => a.id === "sonarr" && a.enabled)
  if (sonarrApp) {
    const apiKey = await getAppApiKey("sonarr")
    if (apiKey) {
      const port = sonarrApp.port ?? 8989
      recyclarrConfig.sonarr = {
        sonarr_main: {
          base_url: `http://sonarr:${port}`,
          api_key: apiKey,
          quality_definition: {
            type: QUALITY_DEFINITIONS.sonarr,
          },
          custom_formats: [
            {
              trash_ids: UNWANTED_CFS.sonarr,
              quality_profiles: DEFAULT_PROFILES.sonarr.map((name) => ({ name })),
            },
          ],
        },
      }
      debugLog("Recyclarr", "Added Sonarr configuration")
    } else {
      debugLog("Recyclarr", "Sonarr enabled but no API key found - skipping")
    }
  }

  // Generate YAML
  const yamlContent = YAML.stringify(recyclarrConfig, {
    indent: 2,
    lineWidth: 0,
  })

  // Add header comment
  const header = `# Recyclarr Configuration
# Generated by easiarr - https://github.com/muhammedaksam/easiarr
# 
# This configuration syncs TRaSH Guides profiles to your *arr apps.
# Recyclarr runs daily via cron to keep profiles up to date.
#
# For more options, see: https://recyclarr.dev/reference/configuration/
#
# To manually trigger sync: docker compose run --rm recyclarr sync
#

`

  return header + yamlContent
}

/**
 * Save recyclarr.yml to the config directory
 */
export async function saveRecyclarrConfig(config: EasiarrConfig): Promise<string> {
  const recyclarrDir = join(config.rootDir, "config", "recyclarr")
  await mkdir(recyclarrDir, { recursive: true })

  const configContent = await generateRecyclarrConfig(config)
  const configPath = join(recyclarrDir, "recyclarr.yml")

  await writeFile(configPath, configContent, "utf-8")
  debugLog("Recyclarr", `Saved recyclarr.yml to ${configPath}`)

  return configPath
}

/**
 * Get the path to the recyclarr config file
 */
export function getRecyclarrConfigPath(config: EasiarrConfig): string {
  return join(config.rootDir, "config", "recyclarr", "recyclarr.yml")
}
