/**
 * Slskd Config Generator
 * Generates slskd.yml configuration file with API keys and settings
 * Source: https://github.com/slskd/slskd/blob/master/docs/config.md
 */

import type { EasiarrConfig } from "./schema"
import { readEnvSync } from "../utils/env"
import { randomBytes } from "crypto"

/**
 * Generate a random API key (base64, 48 bytes = ~64 chars)
 * Equivalent to: openssl rand -base64 48
 */
export function generateSlskdApiKey(): string {
  return randomBytes(48).toString("base64")
}

/**
 * Generate slskd.yml content
 * This file should be placed in the slskd config directory (/app/slskd.yml)
 */
export function generateSlskdConfig(_config: EasiarrConfig): { yaml: string; apiKey: string } {
  const env = readEnvSync()

  // Generate or use existing API key
  const apiKey = env.API_KEY_SLSKD || generateSlskdApiKey()

  const yaml = `# Slskd Configuration
# Generated by Easiarr
# Docs: https://github.com/slskd/slskd/blob/master/docs/config.md

# Directories for downloads
directories:
  incomplete: /data/slskd_downloads/incomplete
  downloads: /data/slskd_downloads/complete

# Shares - music directory for uploading
shares:
  directories:
    - /data/media/music

# Web UI Configuration
web:
  port: 5030
  authentication:
    disabled: false
    api_keys:
      # API key for Homepage widget and Soularr
      easiarr:
        key: ${apiKey}
        role: readwrite
        cidr: 0.0.0.0/0,::/0

# Soulseek Configuration
# Credentials are set via environment variables:
# - SLSKD_SLSK_USERNAME
# - SLSKD_SLSK_PASSWORD
soulseek:
  listen_port: 50300
  description: "slskd user via Easiarr"

# Global limits
global:
  upload:
    slots: 10
    speed_limit: 1000
  download:
    slots: 100
    speed_limit: 10000

# Logging
logger:
  disk: false
`

  return { yaml, apiKey }
}

/**
 * Get the path where slskd.yml should be saved
 */
export function getSlskdConfigPath(rootDir: string): string {
  return `${rootDir}/config/slskd/slskd.yml`
}
